### ISSUE TITLE
display rotation?

### ISSUE THREAD

**Issue by seatosummit** [IndyJoeA/CANgage#1]
Is it possible to rotate the render output 180 degrees? This would make my particular installation idea easier to execute. Cheers

**Comment by IndyJoeA** [comment]
Yes, good idea. This will be added to the next version, 1.0.1.

**Comment by IndyJoeA** [comment]
This was added to [release 1.0.1](https://github.com/IndyJoeA/CANgage/releases/tag/v.1.0.1-TDS3A%2FL)
