### ISSUE TITLE
Display will not render after powercycle

### ISSUE THREAD

**Issue by seatosummit** [IndyJoeA/CANgage#2]
Following a power on reset (ESP32 terminology, as I recall for external power cycle), the display fails to render content. 

The webserver initializes and is accessible on the LAN, however. Calling a software CPU reset via the utility button for "reset" causes the display to come to life as expected.

**Comment by danpadure** [comment]
try powering it from a notebook
I have the same issue when using Tesla's USB port or even a 12V-5V adapter
But all works fine when powering it from a notebook

**Comment by IndyJoeA** [comment]
This has been fixed in release 1.0.2
